### ISSUE TITLE
any thoughts on globbing?

### ISSUE THREAD

**Issue by juhp** [luke-clifton/shh#10]
Is globbing something to be considered, or better avoided/frowned on? :)

**Comment by luke-clifton** [comment]
I have a few ideas in the pipeline. But it's always going to be explicit.

**Comment by luke-clifton** [comment]
So, for now, you can use the [Glob](https://hackage.haskell.org/package/Glob) library and do something like

```
cat =<< glob "*.md"
```

Which isn't too bad, and I might decide that it is the best option.

### Alternate Ideas (all worse then above in my eyes, but experience will tell me more)

I have considered making `IO [String]` an instance of `ExecArg` which would allow you to di

```
cat (glob "*.md")
```

But that brings IO into some nasty places that I rather wouldn't.

I've also considered adding a special case for globbing in how arguments are handled, but there are many types of globbing and pattern matching that people might want to do, and specialy casing it isn't super appealing.

So, I'm planning on holding off for now.

**Comment by luke-clifton** [comment]
I've added a section to the README about how to do globbing.

**Comment by juhp** [comment]
Thanks a lot, this is very helpful :+1:
