### ISSUE TITLE
shh-app.hs "requires" shh-extras

### ISSUE THREAD

**Issue by juhp** [luke-clifton/shh#11]
I am not sure how to fix this without making a separate shell package or merging shh and shh-extras, but anyway just noting that:

```
$ cabal install shh
$ shh
Shh home is: /home/petersen/.shh
GHCi, version 8.4.4: http://www.haskell.org/ghc/  :? for help

<no location info>: error:
    Could not find module ‘Shh.Prompt’
    It is not a module in the current program, or in any known package.

<interactive>:1:2: error:
    Variable not in scope:
      formatPrompt :: [Char] -> [String] -> Int -> IO String
Loaded GHCi configuration from /home/petersen/.shh/init.ghci
[1 of 1] Compiling Shell            ( /home/petersen/.shh/Shell.hs, interpreted )
Ok, one module loaded.
*Shell Shh> 
```

Anyway it is easy to install shh-extras of course, but it would be kind of nice if it got installed/updated together with shh. :)

Also wanted to say that shh is very exciting!

**Comment by luke-clifton** [comment]
Yep, that is a poor user experience.

I've just pushed some changes (and made a hackage release) that addresses this somewhat. We now check your environment for `shh` and `shh-extras` packages when generating the `$SHH_DIR/init.ghci` file. If you have `shh` installed, but not `shh-extras` it prints a warning, and the generated file won't depend on `shh-extras`. If you have neither installed, the process terminates and tells you to remedy the situation.

**Comment by juhp** [comment]
Thanks

I just tried to test a clean install with shh-0.3.1.1, but I seemed to hit the same problem.
Not sure if I am missing something.

**Comment by luke-clifton** [comment]
Indeed. It will only kick in when it's generating an initial `init.ghci`. If you delete that, then run it, it will warn you. It does not do that check each time.

So, new users should get the warning, but existing users will have to know what they are doing.

**Comment by juhp** [comment]
Okay cool, that makes sense - will try deleting the config file, thanks

**Comment by luke-clifton** [comment]
Just to expand on this a bit, your suggestion of merging the packages only works if installing `shh` the executable also installs `shh` the library in a location that your `ghci` will be able to find it. This is true of `cabal install`, and possibly of some other package managers, but is not true for, say, Nix, or if I build a statically linked binary and copy it to a system.

So, doing a simple run-time check on first use is hopefully enough to get the user up and running. Hopefully we can, from that point on, just rely on the error messages from GHC to be sufficient to guide people to the correct solution to their problems.

**Comment by juhp** [comment]
(I didn't see any error on upgrading to 0.3.1.3 fwiw.)

Thanks for the explanation.
