### ISSUE TITLE
2to3 confuses shh

### ISSUE THREAD

**Issue by juhp** [luke-clifton/shh#13]
Not such a big deal but the python tool `/usr/bin/2to3` confuses shh:

```
/home/petersen/.shh/Shell.hs:4:3: error:
    Illegal variable name: ‘2to3’
    When splicing a TH declaration:
      2to3 :: forall a . (Shh.Internal.Unit a,
                    Shh.Internal.ExecArgs a) =>
        a
  |
4 | $(loadEnv SearchPath)
  |   ^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.
```

For now I feel it would be okay to ignore programs starting with a number.
Or any idea how to handle them?

**Comment by luke-clifton** [comment]
We actually run program names through an encoder. The case of starting with a number seems to have regressed. I've updated it and released the fix.

Names that begin with a number are now prefixed with an `_`. So `2to3` becomes `_2to3`.

**Comment by juhp** [comment]
Thanks for fixing: 0.3.1.3 looks good
