### ISSUE TITLE
docs: compare to shelly, turtle, shell-conduit

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#21]
Hey,

this lib looks very cool. I am curious how this relates to other existing libs.

I'd love to read just some quick words what the difference is in your opinion.

Thanks!

**Comment by luke-clifton** [comment]
Yes, I've been meaning to write up a comparison. Until then, a really brief summary (I'm on mobile right now):

* Shh does not go via a shell like most other similar libraries.
* Shh uses real pipes for joining processes together. Shelly and turtle go via Haskell and use some streaming libraries. Shh is more efficient in this regard, though, I don't have benchmarks currently.
* Shh can run directly in IO, no need for ` run` commands.
* Shelly solves the async `cd` problem, shh does not currently.
* Shh is the only one that is usable interactively as a shell replacement

I need to perform a more thorough review to give a more detailed answer, but I suspect error handling is slightly different as well.

I'll try and get something more complete into the doc this week.

**Comment by luke-clifton** [comment]
Oh, and based on your recent question in the NixOS mailing list... Shh specifically has a way of embedding the full path of executables in order for those to be captured by the nix closure as runtime dependencies.

**Comment by maralorn** [comment]
Thank you very much for that explanation. Also the full path feature sounds nice.

**Comment by maralorn** [comment]
I actually have a question in regard to your last point.
Do you have a trick for pulling a dependency into the environment when using pkgs.writeHaskellBin?
With shelly I would do

    run "${pkgs.git}/bin/git status"

or something. Which could contain typos, which would not be found at compile time. With shh I should be something like

    git "status"

But this will obviously fail to build, because the nix derivation will not provide the git pkg. So basically I am wondering how can I get the compile time guarantees from shh combined with the explicit dependency specification of nix

I guess one solution would be an altered writeHaskellBin which has a runtime dependency option. But I am not sure if I like that approach, because it has more overhead compared to writeShellScriptBin. 

What do you think?

**Comment by luke-clifton** [comment]
So, I just added an alternative to `loadEnv`. [`loadFromBins`](http://hackage.haskell.org/package/shh-0.4.0.1/docs/Shh.html#v:loadFromBins)

It takes a list of directories, and scans the `bin` subdirectory for executables. So just pass it in the derivations.

This can be used like this from `writeHaskellBin`

```
{-# LANGUAGE TemplateHaskell #-}

loadFromBins ["${git}"]

main = git "--help"
```

**Comment by luke-clifton** [comment]
Of course, you will need to wait for 0.4.0.1 to get into nixpkgs, but here is a demo running where I build the library from my local copy.

```
nix-repl> :b writers.writeHaskellBin "sa" {libraries = [(haskellPackages.callCabal2nix "shh" /Users/luke/src/shh/shh {})];} ''
          {-# LANGUAGE TemplateHaskell #-}
          import Shh
          loadFromBins ["${git}"]
          main = git "--help"
          ''
[1 built, 0.0 MiB DL]

this derivation produced the following outputs:
  out -> /nix/store/x9nsxlklxr0gsb7mjb3fnrq8bsp3sn3z-sa

[1 built]

[luke@C02P92QNG3QP:~]$ /nix/store/x9nsxlklxr0gsb7mjb3fnrq8bsp3sn3z-sa/bin/sa
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:
```

**Comment by maralorn** [comment]
I'm amazed. Thank you so much!

**Comment by maralorn** [comment]
Awesome!
