### ISSUE TITLE
easy argument parsing

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#26]
Do you have a recommended way to introduce some ad-hoc (but still somehow checked) argument parsing into the script?
Right now I‘m using the cmdargs library, which works fine but often doubles the length of the script I use it in.

---
As you may have noticed I am having a lot of fun with `shh` it’s quite awesome. I hope it’s not annoying, that I am opening so many issues, especially since some of them are really no bugs and I am of course not entitled to any new features.
But this is the easiest way to ask questions.

**Comment by luke-clifton** [comment]
I don't have any particular recommendation for lightweight argument parsing. If it's just a hacky script I tend to just pattern match on `getArgs`.

```
[host, port] <- getArgs
```

Which will at least yell at you if you miss something... but isn't really flexible.

Or if I want more I pull in opt-parse applicative.

---

Please keep posting issues! I'm glad you are having fun with it.

**Comment by luke-clifton** [comment]
Maybe try http://hackage.haskell.org/package/optparse-generic-1.3.0/docs/Options-Generic.html

**Comment by maralorn** [comment]
The getArgs solutions works fine for now. thx!

**Comment by luke-clifton** [comment]
I'm going to close this, as it falls just outside the scope for shh. My intention here is to encourage use of existing command line argument parsing libraries.
