### ISSUE TITLE
Installation with cabal new-install is broken

### ISSUE THREAD

**Issue by kozross** [luke-clifton/shh#28]
If you try something like

```
cabal new-install -O2 shh
```
Then the installation succeeds. However, as soon as you try to execute ``shh``, you get this error:

```
[koz@Sebastian ~]$ shh
Shh home is: /home/koz/.shh
/home/koz/.shh/wrapper: line 2: exec: ghc-pkg: not found
Please make the shh and shh-extras packages available in the shh
environment (install it globally or modify the wrapper, see docs).
Aborting
```
Is there a workaround for this? If so, is there any way to have this 'Just Work' from a ``cabal new-install`` installation?

**Comment by luke-clifton** [comment]
Sounds like you don't have GHC installed globally?

**Comment by luke-clifton** [comment]
Additional comments regarding this: I am thinking of re-writing shh to implement it's own GHCi like REPL. And that is a goal for the 1.0.0.0 release. Currently focus is more on the library.

**Comment by kozross** [comment]
@luke-clifton No, I use a local GHC which I pass to ``cabal`` via its ``-w`` argument. I guess at the moment a global GHC is a requirement?

**Comment by luke-clifton** [comment]
This is where the `wrapper` script could help you. You might be able to append the relevant paths to your PATH environment variable in the wrapper script so that `shh` can find GHCi.

**Comment by kozross** [comment]
There's more to it than that - even if I add the (local) path where ``ghci`` resides, it still can't find ``shh`` and ``shh-extras``. As I'm not too sure how ``cabal new-install`` works, I might have to defer that to someone more knowledgeable. Happy to wait though.

**Comment by luke-clifton** [comment]
It seems the answer is

```
cabal new-install --lib shh
cabal new-install --lib shh-extras
```

Can you see if that works for you? If so, I'll add it to the readme.

**Comment by kozross** [comment]
```sh
[koz@Emi ~]$ cabal new-install --overwrite-policy=always -w /home/koz/ghc-86/bin/ghc -O2 --lib shh
Resolving dependencies...
Up to date
[koz@Emi ~]$ cabal new-install --overwrite-policy=always -w /home/koz/ghc-86/bin/ghc -O2 --lib shh-extras
Resolving dependencies...
Up to date
[koz@Emi ~]$ shh
Shh home is: /home/koz/.shh
ghc-pkg: cannot find package shh
Please make the shh and shh-extras packages available in the shh
environment (install it globally or modify the wrapper, see docs).
Aborting
```

Did I do something incorrectly?

**Comment by luke-clifton** [comment]
So, if you run `/home/koz/ghc-86/bin/ghc-pkg list` does `shh` appear in the output?

If it does appear, make sure your `/home/koz/.shh/wrapper` file look like this:

```
#! /usr/bin/env bash
export PATH="/home/koz/ghc-86/bin:$PATH"
exec "$@"
```

If that doesn't work, I'll see if I can replicate your setup later this weekend.

**Comment by kozross** [comment]
No, it does not. Here is the relevant shell output:

```sh
[koz@Sebastian ~]$ cabal new-install -w /home/koz/ghc-86/bin/ghc -O2 --overwrite-policy=always --lib shh shh-extras
Resolving dependencies...
Up to date
[koz@Sebastian ~]$ /home/koz/ghc-86/bin/ghc-pkg list | grep shh
[koz@Sebastian ~]$ /home/koz/ghc-86/bin/ghc-pkg list 
/home/koz/ghc-86/lib/ghc-8.6.5/package.conf.d
    Cabal-2.4.0.1
    array-0.5.3.0
    base-4.12.0.0
    binary-0.8.6.0
    bytestring-0.10.8.2
    containers-0.6.0.1
    deepseq-1.4.4.0
    directory-1.3.3.0
    filepath-1.4.2.1
    ghc-8.6.5
    ghc-boot-8.6.5
    ghc-boot-th-8.6.5
    ghc-compact-0.1.0.0
    ghc-heap-8.6.5
    ghc-prim-0.5.3
    ghci-8.6.5
    haskeline-0.7.4.3
    hpc-0.6.0.3
    integer-gmp-1.0.2.0
    libiserv-8.6.3
    mtl-2.2.2
    parsec-3.1.13.0
    pretty-1.1.3.6
    process-1.6.5.0
    rts-1.0
    stm-2.5.0.0
    template-haskell-2.14.0.0
    terminfo-0.4.1.2
    text-1.2.3.1
    time-1.8.0.2
    transformers-0.5.6.2
    unix-2.7.2.2
    xhtml-3000.2.2.1
```

This appears to only contain 'core' GHC stuff, rather than anything else I have around (I have HLint and ShellCheck installed via ``cabal new-install``, and they definitely drag in considerable extra libraries).

**Comment by luke-clifton** [comment]
So, the issue seems to be that `ghc-pkg` ignores ghc environment files. Shh is using `ghc-pkg` to check that certain libraries are installed in a pre-flight check before generating the default configuration.

https://github.com/luke-clifton/shh/blob/897024df99341f499752f6cc58cf2e1c8b53626d/shh/app/shh-app.hs#L86-L101

This was originally added to improve the user experience of an initial install https://github.com/luke-clifton/shh/issues/11. Seems to be backfiring on us 😅 

I'll investigate how we can more accurately determine if packages are installed. In the mean time, you can manually initialize the files in the `~/.shh` directory. Here is what the default contents should look like..

```
[~/.shh]$ cat Shell.hs
{-# LANGUAGE TemplateHaskell #-}
module Shell where
import Shh
$(loadEnv SearchPath)

[~/.shh]$ cat init.ghci
:seti -XNoOverloadedLists
import Shh
import Shh.Prompt
:set prompt-function formatPrompt "\n\ESC[1;32m[%u@%h:%w]λ \ESC[0m"
:set prompt-cont "| "

[~/.shh]$ cat wrapper
#! /usr/bin/env sh
exec "$@"
```

With those files in place, you should be good to go. I'll keep this issue open until I have a proper fix released.

**Comment by luke-clifton** [comment]
I've updated it to use `ghc` directly to determine if a library is installed. It's somewhat slower, but because this only occurs on first run to generate the initial configuration files, I'm OK with it.

It's released as 0.7.0.1 on hackage just now.

I've tried to recreate your exact scenario (with the GHC not on path).

```
~$ # GHC not on path
~$ which ghc
~$ rm -Rf .cabal
~$ rm -Rf .ghc
~$ rm -Rf .shh
~$ cabal new-update
... snip ...
Downloading the latest package list from hackage.haskell.org
~$ # Upgraded version
~$ cd src/shh/
shh$ cabal new-install -w /Users/luke/.ghcup/ghc/8.6.5/bin/ghc shh
... snip ...
Symlinking 'shh'
Symlinking 'shh-example'
shh$ cabal new-install -w /Users/luke/.ghcup/ghc/8.6.5/bin/ghc --lib shh-extras
... snip ...
~$ cd
~$ # Due to non-standard GHC install, we need to tell Shh where to find it. This is done
~$ # by modifying the ~/.shh/wrapper script
~$ mkdir .shh
~$ vim .shh/wrapper
~$ cat .shh/wrapper
#! /usr/bin/env sh
PATH=/Users/luke/.ghcup/bin:$PATH
exec "$@"
~$ ~/.cabal/bin/shh
Shh home is: /Users/luke/.shh
Generating init.ghci...
 ... checking for shh...
Loaded package environment from /Users/luke/.ghc/x86_64-darwin-8.6.5/environments/default
Some flags have not been recognized: prompt2, |
 ... checking for shh-extras...
Loaded package environment from /Users/luke/.ghc/x86_64-darwin-8.6.5/environments/default
Some flags have not been recognized: prompt2, |
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Loaded package environment from /Users/luke/.ghc/x86_64-darwin-8.6.5/environments/default
Some flags have not been recognized: prompt2, |
Loaded GHCi configuration from /Users/luke/.ghci
Loaded GHCi configuration from /Users/luke/.shh/init.ghci
Ok, one module loaded.
~$ shh
... launches shell ...
```

Hopefully this resolves the issue.

**Comment by kozross** [comment]
I'm not sure what I'm doing wrong here, but this is what I get when I try:

```sh
[koz@Emi ~]$ cabal new-update
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal new-update 'hackage.haskell.org,2019-08-15T05:26:23Z'
[koz@Emi ~]$ cabal new-install -O2 -w /home/koz/ghc-86/bin/ghc --overwrite-policy=always shh
Resolving dependencies...
Up to date
Symlinking 'shh-example'
Symlinking 'shh'
[koz@Emi ~]$ cabal new-install -O2 -w /home/koz/ghc-86/bin/ghc --overwrite-policy=always shh-0.7.0.2
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: shh (user goal)
[__0] rejecting: shh-0.7.0.2 (constraint from user target requires ==0.7.0.0)
[__0] rejecting: shh-0.7.0.1, shh-0.7.0.0, shh-0.6.0.0, shh-0.5.0.0,
shh-0.4.0.1, shh-0.4.0.0, shh-0.3.1.3, shh-0.3.1.2, shh-0.3.1.1, shh-0.3.1.0,
shh-0.3.0.1, shh-0.3.0.0, shh-0.2.0.6, shh-0.2.0.5, shh-0.2.0.4, shh-0.2.0.3,
shh-0.2.0.2, shh-0.2.0.1, shh-0.2.0.0, shh-0.1.1.0, shh-0.1.0.1, shh-0.1.0.0
(constraint from user target requires ==0.7.0.2)
[__0] fail (backjumping, conflict set: shh)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: shh
```

**Comment by luke-clifton** [comment]
Looks like cabal thinks there is a constraint somewhere that `shh` needs to be version 0.7.0.0

```
[__0] rejecting: shh-0.7.0.2 (constraint from user target requires ==0.7.0.0)
```

To fix this remove `shh` from your `~/.ghc/*/environments/default` file.

**Comment by luke-clifton** [comment]
(Maybe adding `--lib` to your new-install command would work as well?)

**Comment by kozross** [comment]
Removing ``shh`` from the ``default`` file helped the installation. However, I'm still getting the same issue trying to run:

```sh
[koz@Sebastian ~]$ cat .shh/wrapper 
#! /usr/bin/env sh
PATH=/home/koz/ghc-86/bin:$PATH
exec "$@"
[koz@Sebastian ~]$ shh
Shh home is: /home/koz/.shh
ghc-pkg: cannot find package shh
Please make the shh and shh-extras packages available in the shh
environment (install it globally or modify the wrapper, see docs).
Aborting
```

**Comment by luke-clifton** [comment]
```
ghc-pkg: cannot find package shh
```

Double check that it actually installed 0.7.0.2. That is from the old version.

**Comment by kozross** [comment]
You were right - it seems (for whatever reason), ``cabal new-install`` symlinks to the old version instead. Works now! Thank you for your patience and hard work.
