### ISSUE TITLE
Is it possible to use TH load helper with OverloadedStrings?

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#34]
`OverloadedStrings` is a very common extension, that I‘d like to enable sometimes when using shh. Currently `loadFromBins` fails because the Code generate by the the template Haskell then has some Strings with unclear types.
```
tmp.hs:23:1: error:                                                                                                    
                   GHC.Stack.Types.HasCallStack => a       
    * Could not deduce (ExecArg str118) arising from a use of `exe'                                                    
        at tmp.hs:22:1-144                                                                                             
```

**Comment by luke-clifton** [comment]
If using OverloadedStrings I also recommend enabling ExtendedDefaultRules. This will solve your issue.

**Comment by luke-clifton** [comment]
It's in the [README](https://github.com/luke-clifton/shh/blob/master/shh/README.md), though perhaps it needs to be more obvious, perhaps in the haddock as well.

**Comment by maralorn** [comment]
I must admit I had overlooked that. But I also had no expectation to find a solution there.

Thanks!
