### ISSUE TITLE
Output ordering

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#37]
I have a script which has the following two lines in do notation:

```haskell
putStrLn "Trying build …"
nix_build ...
```

I am compiling the script `-threaded`. What I see is the following:
```
<all output from nix-build>
Trying build ...
```
It is deterministically always in the wrong order, even when the build takes minutes. Changing `putStrLn` to `say` from the Say package didn‘t help. Do you have any idea why this could be happening?

**Comment by luke-clifton** [comment]
Have you tried putting a

```
hFlush stdout
```
Between the two lines?

Other option would be to ensure stdout is line buffered.

**Comment by maralorn** [comment]
The `hFlush` was enough. As always you are a great help. Thank you very much!

**Comment by luke-clifton** [comment]
Perhaps it would be worthwhile modifying the library to always call `hFlush` on `stdout` and `stderr` before executing a command.

**Comment by maralorn** [comment]
I have no clue about the performance implication that has. But yeah, I think I‘d prefer the batteries included approach.

**Comment by luke-clifton** [comment]
I've made a new release [v0.7.0.8](https://github.com/luke-clifton/shh/tree/shh-0.7.0.8) which does this.
