### ISSUE TITLE
nixpkgs tests failing

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#39]
Could you have a look at those tests and can tell me if they are easily fixable, e.g. by just adding one or two dependencies, or something?
That would be very nice!

https://hydra.nixos.org/build/120232866/nixlog/1

If not I will just disable them.

**Comment by luke-clifton** [comment]
It's probably wise to disable tests due to https://github.com/NixOS/nix/issues/2803 which will cause test failure on incorrectly configured nix daemons (including ones in the hydra pool).

From my experience, the timeouts in the tests tend to be when the system is under load.

**Comment by maralorn** [comment]
Done in: https://github.com/NixOS/nixpkgs/pull/89001
