### ISSUE TITLE
The documentation for captureEndBy0 and captureLines is incorrectly rendered

### ISSUE THREAD

**Issue by expipiplus1** [luke-clifton/shh#45]
in my haddocks it says;

```
Same as captureEndBy "0".
..
Same as captureSplit "n".
```

My context clues suggest that theses should be `"\0'` and `"\n"`

Thanks for the great library by the way, I'm enjoying using it so far!

**Comment by luke-clifton** [comment]
Thanks, I always mess up the haddock syntax for those....

**Comment by expipiplus1** [comment]
Thanks!
