### ISSUE TITLE
Restrictive upper bounds on base and template-haskell

### ISSUE THREAD

**Issue by maralorn** [luke-clifton/shh#76]
Just a heads up: Currently shh has these bounds:
```
Error: Setup: Encountered missing or private dependencies:
base >=4.9 && <4.17, template-haskell >=2.13.0 && <2.19
```
but it builds fine with ghc 9.4 which have newer base and newer template-haskell.

**Comment by luke-clifton** [comment]
Thanks for the heads up. I'll bump bounds and release on Monday when I'm back at my machine.

**Comment by luke-clifton** [comment]
I've release 0.7.2.2 which also fixes some deprecation warnings.

**Comment by maralorn** [comment]
There is still the same problem for shh-extras.

**Comment by luke-clifton** [comment]
I've done a metadata revision on hackage.
