### ISSUE TITLE
withFrozenCallStack

### ISSUE THREAD

**Issue by ScottFreeCode** [luke-clifton/shh#79]
The doc for `exe` suggests wrapping it in `withFrozenCallStack`, but the implementation for `exe` already calls `withFrozenCallStack`; isn't this redundant? Likewise `rawExe` also wraps the call to `exe` in `withFrozenCallStack` which looks redundant.

**Comment by ScottFreeCode** [comment]
(For what it's worth I don't know what withFrozenCallstack does, so maybe these aren't redundant?)

**Comment by luke-clifton** [comment]
`withFrozenCallStack` just means that when the program fails, it prints out a better name and location, without falling into the internals of Shh.

Compare:

```
$ runhaskell example_with_no_frozen.hs
example.hs: Command `false` failed [exit 1] at CallStack (from HasCallStack):
  exe, called at example.hs:5:9 in main:Main
  false, called at example.hs:10:3 in main:Main
```

and 

```
$ runhaskell example_with_frozen.hs
example.hs: Command `false` failed [exit 1] at CallStack (from HasCallStack):
  false, called at example.hs:10:3 in main:Main
```

Seeing that extra `exe` line is distracting, and not pretty. But that is the only thing.

---

This is the `.hs` file:

```
import Shh
import GHC.Stack

false :: Cmd
false = withFrozenCallStack $ exe "false"


main :: IO ()
main = do
  false
```

**Comment by ScottFreeCode** [comment]
Aha. So, the one inside `exe` means `exe` itself is the one line of Shh you would see if you don't use it yourself, whereas you don't even see that if you do use it; and the one in `rawExe` makes the TH-generated `fName = exe executable` actually be `fName = withFrozendCallStack $ exe executable`?

**Comment by luke-clifton** [comment]
Yep.

**Comment by ScottFreeCode** [comment]
Cool; well that answers my question! Thanks!
