### ISSUE TITLE
λ character encoding error

### ISSUE THREAD

**Issue by ScottFreeCode** [luke-clifton/shh#81]
When I run `shh` with `shh-extras` present, I get this error:

> shh: init.ghci: withFile: invalid argument (invalid character)

The init.ghci file appears to end immediately before the λ character in the string in the shh app source code.

I tried a few things to troubleshoot.

An internet search claims the hex code for this unicode character is 03bb. Unfortunately, using `"\x03bb"` in Haskell just prints `?` instead.

Maybe my terminal doesn't support it? But no, I can paste it into my terminal with C+Shift+v and `echo 'λ'` works.

If I paste it into something like `ghc -e 'putStrLn "λ"'` or `ghc -e "putStrLn \"$(wl-paste)\""` then I get this error instead:

> &lt;interactive>:0:11: error:
> &nbsp;&nbsp;&nbsp;&nbsp;lexical error in string/character literal at character '\56526'

I have a feeling this is a problem on my end but I am not really sure what else to look at.

I'm on arm64 / aarch64 for what it's worth. To be precise, DanctNix (a variant of Arch Linux Arm) on the PineTab2 tablet, in the default terminal (Konsole). Haskell is installed using the Nix package manager, I believe its installer gives the aarch64 version of the package manager and repository.

**Comment by iogrt** [comment]
Are you running `ghc -e 'putStrLn "λ"'` with `shh` or outside? because it works perfectly for me outside.
I'm currently not using `ssh` so I can't test it inside but something tells me your machine doesn't support unicode for some reason

**Comment by ScottFreeCode** [comment]
Outside.

I wonder how I would check for Unicode support. The clipboard and terminal is clearly able to paste the character and print it, it's just Haskell that does not like the character. But since I'm also not having any success trying to use hex code 03bb, maybe it's some kind of mismatch between different UTF encodings?

**Comment by ScottFreeCode** [comment]
A couple more things.

- The issue does not occur on NixOS for an x64 laptop.
- `hexdump` reports the character as `bbce`.
- On laptop, Haskell outputs Asian characters for `\xbbce` or `\xcebb`.
- On laptop, Haskell outputs lambda for `\xo3bb`
- On either device (so, this does work on the same tablet where Haskell won't display any of these characters!), `echo -e '\xce\xbb'` outputs lambda.

I'm not sure what's going on with 03bb vs cebb, but it seems like the terminal/echo interprets this fine, and that Haskell does fine on a different device. So it's something about Haskell on the arm tablet.

I guess it's almost certainly not an issue with Shh.

**Comment by juhp** [comment]
Encoding issue perhaps??

**Comment by luke-clifton** [comment]
Indeed, text encoding is kinda annoying here. Worth noting that if your [localeEncoding](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-IO-Encoding.html#v:getLocaleEncoding) and your [fileSystemEncoding](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-IO-Encoding.html#v:getFileSystemEncoding) don't match you are probably going to have some issues.

If I recall correctly, I have made an assumption somewhere that both are "UTF-8b".

This is mainly done because (a) it's a really common to be using some sort of UTF-8 encoding in your terminal these days, and (b) it allows round tripping binary data (in Linux, we allow arbitrary data in the filesystem encoding, but we usually want to display it as if it's unicode when we can).

**Comment by luke-clifton** [comment]
It's also worth noting that Haskell does a poor job of distinguishing between `String`s that are "file system encoded" and `String`s that aren't. Rust got it right here.

https://blog.themk.net/posts/2021-06-28-haskell-filepath-encoding.html

There is also the "Abstract Filepath Proposal" which has recently been implemented in (filepath)[https://hackage.haskell.org/package/filepath-1.4.100.4] which attempts to address some of these.
